--- #YAML:1.0
name:               Device-BCM2835-LCD
version:            0.01
abstract:           Perl extension for driving an HD44780 LCD from a Raspberry Pi's GPIO port
author:
    - Joshua Small <josh@festy.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Device::BCM2835:  1.3
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
